image: golang:1.12.1-stretch

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - lint
  - build
  - test

before_script:
  - apt-get update && apt-get install -y make curl
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - mkdir -p /go/src/gitlab.com/davecremins
  - ln -s /builds/davecremins/safe-deposit-box /go/src/gitlab.com/davecremins
  - cd /go/src/gitlab.com/davecremins/safe-deposit-box

lint:
  stage: lint
  script:
    - go get -u github.com/mgechev/revive
    - revive -config config.toml -formatter stylish /go/src/gitlab.com/davecremins/safe-deposit-box/...

build:
  stage: build
  script:
    - make all

test:
  stage: test
  script:
    - make get
    - make test
